### ISSUE TITLE
Open dialogue with elementary devs to ship with OS

### ISSUE THREAD

**Issue by hanaral** [kvdz/switchboard-backup-plug#3]
Hi - I just stumbled upon this backup plug and think it's the perfect place for it!
However, since it's a plug it likely won't make it to the AppCenter, despite it (imo) being a crucial part of an ideal OS experience. So, I think it's a good opportunity to start some dialogue with some of the elementary team to get this to be a part of a future release!
Tagging @cassidyjames @danrabbit for their input

**Comment by kvdz** [comment]
hi @hanaral , thank you for mentioning this to Cassidy and Daniel. This project is an idea that i had and would like to explore.
therefore it is a personal repository.

i am sometimes active in the elementary community (last couple years less). but to be fair i don't think this repo itself will gain a lot of attention and maybe it will be adopted someday. But i am not counting on it.

if your comfortable with the terminal you might be able to install it from source. but you shouldn't expect it to land in next releases/app center. As of now it doesn't even work yet.
